
package grade_system;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
public class Admin_StudentProfile_Internal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_EnrollStudent_Internal
     */
    public Admin_StudentProfile_Internal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table_ScrollPanel = new javax.swing.JScrollPane();
        PROFILE_TABLE = new javax.swing.JTable();
        REFRESH_BUTTON = new javax.swing.JButton();
        Admin_StudentProfile_Background = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PROFILE_TABLE.setAutoCreateRowSorter(true);
        PROFILE_TABLE.setBackground(new java.awt.Color(204, 204, 204));
        PROFILE_TABLE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PROFILE_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT NAME", "YEAR AND SECTION", "GENDER", "STUDENT NUMBER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PROFILE_TABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PROFILE_TABLE.setGridColor(new java.awt.Color(0, 153, 255));
        PROFILE_TABLE.setShowGrid(true);
        PROFILE_TABLE.setShowHorizontalLines(true);
        PROFILE_TABLE.setShowVerticalLines(true);
        Table_ScrollPanel.setViewportView(PROFILE_TABLE);
        if (PROFILE_TABLE.getColumnModel().getColumnCount() > 0) {
            PROFILE_TABLE.getColumnModel().getColumn(0).setResizable(false);
            PROFILE_TABLE.getColumnModel().getColumn(1).setResizable(false);
            PROFILE_TABLE.getColumnModel().getColumn(2).setResizable(false);
            PROFILE_TABLE.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(Table_ScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 680, 250));

        REFRESH_BUTTON.setBackground(new java.awt.Color(102, 102, 102));
        REFRESH_BUTTON.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        REFRESH_BUTTON.setForeground(new java.awt.Color(102, 255, 204));
        REFRESH_BUTTON.setText("GENERATE");
        REFRESH_BUTTON.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        REFRESH_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFRESH_BUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(REFRESH_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 50));

        Admin_StudentProfile_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grade_system/Admin_StudentProfile (1).png"))); // NOI18N
        Admin_StudentProfile_Background.setToolTipText("");
        getContentPane().add(Admin_StudentProfile_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REFRESH_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFRESH_BUTTONActionPerformed
        
        FileReader File_Reader;
        BufferedReader Buffered_Reader;
        try{
            File_Reader = new FileReader("Students.txt");
            Buffered_Reader = new BufferedReader(File_Reader);
            
            DefaultTableModel model = (DefaultTableModel)PROFILE_TABLE.getModel();
            Object[] Lines = Buffered_Reader.lines().toArray();
            
            for(int i=0; i<Lines.length; i++){
                String[] Row = Lines[i].toString().split("!");
                model.addRow(Row);
            }
            
        } catch (IOException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "THERE'S AN ERROR", "Error In Table", JOptionPane.ERROR_MESSAGE);
        }
        
        REFRESH_BUTTON.setEnabled(false);
            
    }//GEN-LAST:event_REFRESH_BUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_StudentProfile_Background;
    private javax.swing.JTable PROFILE_TABLE;
    private javax.swing.JButton REFRESH_BUTTON;
    private javax.swing.JScrollPane Table_ScrollPanel;
    // End of variables declaration//GEN-END:variables
}
