
package grade_system;
import javax.swing.JOptionPane;
public class Student_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Student_Frame
     */
    public Student_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentNumber_Label = new javax.swing.JLabel();
        Student_Number_Input = new javax.swing.JTextField();
        Student_Password_Label = new javax.swing.JLabel();
        Student_Password_Input = new javax.swing.JPasswordField();
        Student_Enroll_Label = new javax.swing.JLabel();
        Login_Button = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();
        Student_Frame_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentNumber_Label.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        StudentNumber_Label.setForeground(new java.awt.Color(255, 255, 255));
        StudentNumber_Label.setText("STUDENT NUMBER");
        getContentPane().add(StudentNumber_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 190, 30));

        Student_Number_Input.setBackground(new java.awt.Color(204, 204, 204));
        Student_Number_Input.setFont(new java.awt.Font("Lucida Fax", 2, 18)); // NOI18N
        Student_Number_Input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Student_Number_Input.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 51)));
        Student_Number_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_Number_InputActionPerformed(evt);
            }
        });
        getContentPane().add(Student_Number_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 370, 50));

        Student_Password_Label.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Student_Password_Label.setForeground(new java.awt.Color(255, 255, 255));
        Student_Password_Label.setText("PASSWORD");
        getContentPane().add(Student_Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 110, 30));

        Student_Password_Input.setBackground(new java.awt.Color(204, 204, 204));
        Student_Password_Input.setFont(new java.awt.Font("Lucida Fax", 2, 14)); // NOI18N
        Student_Password_Input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Student_Password_Input.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 51)));
        Student_Password_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_Password_InputActionPerformed(evt);
            }
        });
        getContentPane().add(Student_Password_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 370, 50));

        Student_Enroll_Label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        Student_Enroll_Label.setForeground(new java.awt.Color(255, 255, 255));
        Student_Enroll_Label.setText("Don't have an account yet?     Tell an Admin to Enroll you as Student");
        getContentPane().add(Student_Enroll_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, 20));

        Login_Button.setBackground(new java.awt.Color(153, 153, 153));
        Login_Button.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Login_Button.setText("LOG IN");
        Login_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 130, 40));

        Back_Button.setBackground(new java.awt.Color(153, 153, 153));
        Back_Button.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Back_Button.setText("BACK");
        Back_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 130, 40));

        Student_Frame_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grade_system/Student_Login (1).png"))); // NOI18N
        getContentPane().add(Student_Frame_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Student_Number_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_Number_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Student_Number_InputActionPerformed

    private void Student_Password_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_Password_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Student_Password_InputActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed

        //Get the Username and Password of Admin
        String Student_Number = Student_Number_Input.getText();
        String Student_Password = Student_Password_Input.getText();

        //Login Projection of Admin
        String Student_Number_Credential = "Student";
        String Student_Password_Credential = "Secret123";

        if(Student_Number.equals(Student_Number_Credential) && Student_Password.equals(Student_Password_Credential)){

            Student_Dashboard_Frame Dashboard = new Student_Dashboard_Frame();
            setVisible(false);
            Dashboard.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter a Correct Account.","!!ACCOUNT NOT FOUND!!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed

        Grade_System_Main_Frame Main = new Grade_System_Main_Frame();
        setVisible(false);
        Main.setVisible(true);

    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel StudentNumber_Label;
    private javax.swing.JLabel Student_Enroll_Label;
    private javax.swing.JLabel Student_Frame_Background;
    private javax.swing.JTextField Student_Number_Input;
    private javax.swing.JPasswordField Student_Password_Input;
    private javax.swing.JLabel Student_Password_Label;
    // End of variables declaration//GEN-END:variables
}
